DISCORD_API_KEY: ''     # Discord Bot API Token
DISCORD_ADM_CHAT_ID: '' # Id чата, куда будет отправляться всё из админского чата
DISCORD_ALL_CHAT_ID: '' # Id чата, куда будет отправлятся весь игровой чат